DROP TABLE AVIONES IF EXISTS;

CREATE TABLE AVIONES(
ID INT AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
MATRICULA VARCHAR(50) NOT NULL,
FECHA-ENTRADA-SERVICIO DATE NOT NULL
);


INSERT INTO AVIONES VALUES (DEFAULT,'Boeing', '2010', '559988', '2010-3-15');